import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomTabNavigator from "./components/BottomTabNav";
import { TelegramContextProvider } from "./context/TelegramProvider";
import { VideoContextProvider } from "./context/videoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TelegramContextProvider>
      <VideoContextProvider>
          {children}
          <div>
            <BottomTabNavigator />
          </div>
        </VideoContextProvider>
        </TelegramContextProvider>
      </body>
    </html>
  );
}